name: Check winning numbers

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'

jobs:
  Number-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Get and check numbers
        run: |
            pip install requests
            pip install beautifulsoup4
            python advent.py > ./result.md
            source xenv.sh
            gh issue create -t "$GH_ISSUE_TITLE" -F ./result.md
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}